### ISSUE TITLE
Inconsistent capitalization

### ISSUE THREAD

**Issue by rnobleeddy** [capitalone/dataCompareR#40]
Running 

```
rm(list=ls())

library(dataCompareR)


#dataCompare will match data frames (or any objects that can be coerced to data frames) - this is part of the package (uses as.data.frame)

#Lets use iris in the first example
head(iris)

#Create a new data frame to use in dataCompareR

#Make a copy of iris
iris2 <- iris

#Change it by first subsetting just to the first 140 rows:
iris2 <- iris[1:140,]

#then remove Petal.Width column
iris2$Petal.Width <- NULL

#and then change some values
iris2[1:10,1] <- iris2[1:10,1] + 1

#Comparison without a key:
#Rows are matched based on order: if the dataframes have different number of rows then rows will be dropped from the larger data frame
#This will be recorded in the output

#Run the comparison
compIris <- rCompare(iris,iris2)


summary(compIris)
```

Results in 

```
Columns only in iris: Petal.Width  
Columns in both : PETAL.LENGTH, SEPAL.LENGTH, SEPAL.WIDTH, SPECIES 
```

We're kinda stuck with capitals as we have no easy way of recovering the original case, but the first row should be capitals too!

**Comment by RjLi13** [comment]
Hi rnobleeddy, I think I found an easy fix and put the solution in out_unifiedOutputGenerator.R. My fix is to capitalize the character vector that prints out the column names in summaryReport. The only issue is that the tests fail in testMakeValidNames because it checks for exact string matching, not equality without case. Do you have a suggestion for a better place to put the fix or change the tests up to accommodate the fix?

**Comment by rnobleeddy** [comment]
Sorry for the delay in responding - in this case, I think it's best to change the tests - this also captures testing that your change is working.
