### ISSUE TITLE
Update README to show off the package

### ISSUE THREAD

**Issue by rnobleeddy** [capitalone/dataCompareR#47]
I'm not sure pointing at the vignette is wise. The top of the `README` is probably the place to show off what the package does?

**Comment by RjLi13** [comment]
Hey rnobleeddy, I think I'd like to take a stab at this if it is still an issue that should be solved. Based on your suggestion, should we get rid of the vignette and put the information on the README instead? Or extract parts of the vignette such as a more detailed summary and the functions available to the user?

**Comment by rnobleeddy** [comment]
Again, apologies for the slow reply.

I think the vignette is probably OK, but we should add a little of the content to the README. For example, the top of https://github.com/tidyverse/dplyr/blob/master/README.md has the main info about what the package does. I'm not entirely sure how we'd do this for this package, but it's probably a better advertisement if there's a little more about how the package works at the top of the README. 

Let me know own if you disagree?

**Comment by RjLi13** [comment]
Perhaps we can add the functions that are exposed for the end user to use along with a short description, much like the link you sent? For the content of the top of the README, we could copy the top of vignette. Then, replace the top of the vignette with a 1-2 sentence blurb introducing an example workflow. 

The vignette intro feels to be at the wrong place because the user would know what the project is about already through the README. It fits better as the top of the README. I can present a pull request of a changed README/vignette if this is agreeable?

**Comment by RjLi13** [comment]
Also, I am facing an issue with the second install option with devtools and `install_git`. This seems to be a Mac issue currently broken as shown [here](https://github.com/ropensci/git2r/issues/331). If this isn't merely my own environment issue, I'd like to also add a note warning Mac users that the second install option currently does not work.

**Comment by RjLi13** [comment]
I took the opportunity to change both the README and the vignette. If you could take a look and see if something like this fits the bill?
